-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into public.users_roles values ('VIEWER', 'View-only user role');
-- insert into public.users_roles values ('LIBRARY-REVIEWER', 'Author review only user');
-- insert into public.users_roles values ('CENTER-REVIEWER', 'Center/Institute review only user');
-- insert into public.users_roles values ('ADMIN', 'Admin user that can access all tabs');
