version: '3.7'

services:
  postgres:
      image: postgres:13.4
      environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - ${POSTGRES_PORT}:5432
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ${DUMP_PATH}:/tmp/backup.sql
        - ./build/keycloak/init.sql:/docker-entrypoint-initdb.d/1-keycloak.sql
        - ./build/hasura/init.sql:/docker-entrypoint-initdb.d/2-hasura.sql
  
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-beta.2
    ports:
      - ${HASURA_PORT}:8080
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${HASURA_DATABASE}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_ENABLE_CONSOLE}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_AUTH_HOOK: http://${DOCKER_HOST_IP}:8000/${HASURA_WEBHOOK}

volumes:
  postgres_data:
