version: '3.7'

services:
  postgres:
      image: postgres:9.6
      environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - ${POSTGRES_PORT}:5432
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ${KEYCLOAK_DUMP}:/tmp/keycloak.sql
        - ${HASURA_DUMP}:/tmp/hasura.sql
        - ./build/templates/keycloak/init.sql:/docker-entrypoint-initdb.d/1-keycloak.sql
        - ./build/templates/hasura/init.sql:/docker-entrypoint-initdb.d/2-hasura.sql
        - ./build/templates/hasura/restore.sh:/docker-entrypoint-initdb.d/3-restore.sh
volumes:
  postgres_data: