query MyQuery ($personId: Int!, $yearMin: Int!, $yearMax: Int!) {
  confidencesets_persons_publications_aggregate(
    distinct_on: persons_publications_id,
      where: {
        person_id: {_eq: $personId},
        publication: {
          year: {_gte: $yearMin, _lte: $yearMax}
        }
      },
      order_by: {
        persons_publications_id: asc,
        datetime: desc
      }
  ) {
      nodes {
        persons_publications_id
        value
        datetime
      }
  }
}