query MyQuery ($personId: Int!, $userId: Int!, $reviewType: type_review_enum!) {
  persons_publications(
    where: {
      person_id: {_eq: $personId},
      reviews: {
        user_id: {_eq: $userId},
        reviewType: {_eq: $reviewType}
      }
    },
    order_by: {confidence: desc, publication: {title: asc}}
  ) {
    id
    person_id
    publication_id
    publication {
      id
      title
      doi
      csl_string
    }
    person {
      id
      family_name
      given_name
    }
    confidence
    reviews {
      reviewType
    }
  }
}