query MyQuery ($publicationId: Int!) {
  publications(
    where: {
      id: {_eq: $publicationId}
    }
  ) {
    id
    title
    doi
    year
    csl_string
    csl
    source_name
    source_metadata
    scopus_eid: source_metadata(path: "eid")
    pubmed_resource_identifiers: source_metadata(path: "resourceIdentifiers")
    journal {
      title
      journals_classifications_aggregate {
        nodes {
          classification {
            name
            id
            identifier
          }
        }
      }
    }
    csl_subject: csl(path: "subject")
  }
}