query MyQuery ($publicationId: Int!) {
  publications(
    where: {
      id: {_eq: $publicationId}
    }
  ) {
    id
    title
    doi
    year
    csl_string
    csl
    journal_title: csl(path:"container-title")
    source_name
    source_metadata
    scopus_eid: source_metadata(path: "eid")
    wos_id: source_metadata(path: "uid")
    pubmed_resource_identifiers: source_metadata(path: "resourceIdentifiers")
    semantic_scholar_id: source_metadata(path: "paperId")
    journal {
      title
      journals_classifications_aggregate {
        nodes {
          classification {
            name
            id
            identifier
          }
        }
      }
    }
    awards {
      id
      funder_award_identifier
      funder_name
      source_name
    }
    csl_subject: csl(path: "subject")
  }
}