query MyQuery ($userId: Int!, $personId: Int!, $reviewType: String!) {
  reviews(where: 
    {review_type: {_eq: $reviewType}, 
    user_id: {_eq: $userId}}) {
    id
    persons_publication (order_by: {confidence: desc}) {
      id
      person_id
      publication_id
      publication {
        id
        doi
        title
        year
      }
      person {
        id
        family_name
        given_name
      }
      confidence
    }
  }
}
