query MyQuery($names: [String!], $yearMin: Int!, $yearMax: Int!) {
  persons(where: {institution: {name: {_in: $names}}}, order_by: {persons_publications_aggregate: {count: desc}}) {
    id
    given_name
    family_name
    institution {
      name
    }
    persons_publications_aggregate (where: {publication: {year: {_gte: $yearMin, _lte: $yearMax}}}){
      aggregate {
        count
      }
    }
  }
}
