CREATE DATABASE {{ .Env.HASURA_DATABASE }} TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE {{ .Env.HASURA_DATABASE }} TO {{ .Env.POSTGRES_USER }};
\c {{ .Env.HASURA_DATABASE }};
CREATE EXTENSION pgcrypto SCHEMA public;