
CREATE VIEW PERSONS_PUBLICATIONS_METADATA AS
    SELECT 
        PERSONS_PUBLICATIONS.ID, 
        PERSONS_PUBLICATIONS.PERSON_ID, 
        PERSONS_PUBLICATIONS.PUBLICATION_ID, 
        PERSONS_PUBLICATIONS.CONFIDENCE,
        PUBLICATIONS.TITLE,
        PUBLICATIONS.DOI,
        PUBLICATIONS.SOURCE_NAME,
        PUBLICATIONS.YEAR
    FROM PERSONS_PUBLICATIONS, PUBLICATIONS
    WHERE PERSONS_PUBLICATIONS.PUBLICATION_ID = PUBLICATIONS.ID