
      insert into classifications (name, identifier, scheme) values ('General Medicine', '2700', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Medicine (miscellaneous)', '2701', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Anatomy', '2702', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Anesthesiology and Pain Medicine', '2703', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Biochemistry, medical', '2704', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Cardiology and Cardiovascular Medicine', '2705', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Critical Care and Intensive Care Medicine', '2706', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Complementary and alternative medicine', '2707', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Dermatology', '2708', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Drug guides', '2709', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Embryology', '2710', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Emergency Medicine', '2711', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Endocrinology, Diabetes and Metabolism', '2712', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Epidemiology', '2713', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Family Practice', '2714', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Gastroenterology', '2715', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Genetics(clinical)', '2716', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Geriatrics and Gerontology', '2717', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Health Informatics', '2718', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Health Policy', '2719', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Hematology', '2720', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Hepatology', '2721', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Histology', '2722', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Immunology and Allergy', '2723', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Internal Medicine', '2724', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Infectious Diseases', '2725', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Microbiology (medical)', '2726', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Nephrology', '2727', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Clinical Neurology', '2728', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Obstetrics and Gynaecology', '2729', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Oncology', '2730', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Ophthalmology', '2731', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Orthopedics and Sports Medicine', '2732', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Otorhinolaryngology', '2733', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pathology and Forensic Medicine', '2734', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pediatrics, Perinatology, and Child Health', '2735', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pharmacology (medical)', '2736', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Physiology (medical)', '2737', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Psychiatry and Mental health', '2738', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Public Health, Environmental and Occupational Health', '2739', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pulmonary and Respiratory Medicine', '2740', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Radiology Nuclear Medicine and imaging', '2741', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Rehabilitation', '2742', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Reproductive Medicine', '2743', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Reviews and References, Medical', '2744', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Rheumatology', '2745', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Surgery', '2746', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Transplantation', '2747', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Urology', '2748', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Neuroscience', '2800', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Neuroscience (miscellaneous)', '2801', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Behavioral Neuroscience', '2802', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Biological Psychiatry', '2803', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Cellular and Molecular Neuroscience', '2804', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Cognitive Neuroscience', '2805', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Developmental Neuroscience', '2806', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Endocrine and Autonomic Systems', '2807', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Neurology', '2808', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Sensory Systems', '2809', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Nursing', '2900', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Nursing (miscellaneous)', '2901', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Advanced and Specialised Nursing', '2902', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Assessment and Diagnosis', '2903', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Care Planning', '2904', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Community and Home Care', '2905', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Critical Care', '2906', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Emergency', '2907', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Fundamentals and skills', '2908', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Gerontology', '2909', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Issues, ethics and legal aspects', '2910', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Leadership and Management', '2911', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('LPN and LVN', '2912', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Maternity and Midwifery', '2913', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Medical–Surgical', '2914', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Nurse Assisting', '2915', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Nutrition and Dietetics', '2916', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Oncology(nursing)', '2917', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pathophysiology', '2918', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pediatrics', '2919', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pharmacology (nursing)', '2920', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Phychiatric Mental Health', '2921', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Research and Theory', '2922', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Review and Exam Preparation', '2923', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Pharmacology, Toxicology and Pharmaceutics', '3000', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pharmacology, Toxicology and Pharmaceutics (miscellaneous)', '3001', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Drug Discovery', '3002', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pharmaceutical Science', '3003', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pharmacology', '3004', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Toxicology', '3005', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Physics and Astronomy', '3100', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Physics and Astronomy (miscellaneous)', '3101', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Acoustics and Ultrasonics', '3102', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Astronomy and Astrophysics', '3103', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Condensed Matter Physics', '3104', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Instrumentation', '3105', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Nuclear and High Energy Physics', '3106', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Atomic and Molecular Physics, and Optics', '3107', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Radiation', '3108', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Statistical and Nonlinear Physics', '3109', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Surfaces and Interfaces', '3110', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Psychology', '3200', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Psychology (miscellaneous)', '3201', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Applied Psychology', '3202', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Clinical Psychology', '3203', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Developmental and Educational Psychology', '3204', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Experimental and Cognitive Psychology', '3205', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Neuropsychology and Physiological Psychology', '3206', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Social Psychology', '3207', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Social Sciences', '3300', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Social Sciences (miscellaneous)', '3301', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Archaeology', '3302', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Development', '3303', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Education', '3304', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Geography, Planning and Development', '3305', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Health(social science)', '3306', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Human Factors and Ergonomics', '3307', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Law', '3308', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Library and Information Sciences', '3309', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Linguistics and Language', '3310', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Safety Research', '3311', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Sociology and Political Science', '3312', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Transportation', '3313', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Anthropology', '3314', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Communication', '3315', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Cultural Studies', '3316', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Demography', '3317', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Gender Studies', '3318', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Life-span and Life-course Studies', '3319', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Political Science and International Relations', '3320', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Public Administration', '3321', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Urban Studies', '3322', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Veterinary', '3400', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Veterinary (miscalleneous)', '3401', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Equine', '3402', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Food Animals', '3403', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Small Animals', '3404', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Dentistry', '3500', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Dentistry (miscellaneous)', '3501', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Dental Assisting', '3502', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Dental Hygiene', '3503', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Oral Surgery', '3504', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Orthodontics', '3505', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Periodontics', '3506', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Health Professions', '3600', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Health Professions (miscellaneous)', '3601', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Chiropractics', '3602', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Complementary and Manual Therapy', '3603', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Emergency Medical Services', '3604', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Health Information Management', '3605', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Medical Assisting and Transcription', '3606', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Medical Laboratory Technology', '3607', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Medical Terminology', '3608', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Occupational Therapy', '3609', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Optometry', '3610', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pharmacy', '3611', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Physical Therapy, Sports Therapy and Rehabilitation', '3612', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Podiatry', '3613', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Radiological and Ultrasound Technology', '3614', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Respiratory Care', '3615', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Speech and Hearing', '3616', 'ASJC');
  
