
     insert into classifications (name, identifier, scheme) values ('General Chemical Engineering', '1500', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Chemical Engineering (miscellaneous)', '1501', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Bioengineering', '1502', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Catalysis', '1503', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Chemical Health and Safety', '1504', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Colloid and Surface Chemistry', '1505', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Filtration and Separation', '1506', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Fluid Flow and Transfer Processes', '1507', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Process Chemistry and Technology', '1508', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Chemistry', '1600', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Chemistry (miscellaneous)', '1601', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Analytical Chemistry', '1602', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Electrochemistry', '1603', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Inorganic Chemistry', '1604', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Organic Chemistry', '1605', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Physical and Theoretical Chemistry', '1606', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Spectroscopy', '1607', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Computer Science', '1700', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Computer Science (miscellaneous)', '1701', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Artificial Intelligence', '1702', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Computational Theory and Mathematics', '1703', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Computer Graphics and Computer-Aided Design', '1704', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Computer Networks and Communications', '1705', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Computer Science Applications', '1706', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Computer Vision and Pattern Recognition', '1707', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Hardware and Architecture', '1708', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Human-Computer Interaction', '1709', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Information Systems', '1710', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Signal Processing', '1711', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Software', '1712', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Decision Sciences', '1800', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Decision Sciences (miscellaneous)', '1801', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Information Systems and Management', '1802', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Management Science and Operations Research', '1803', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Statistics, Probability and Uncertainty', '1804', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Earth and Planetary Sciences', '1900', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Earth and Planetary Sciences (miscellaneous)', '1901', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Atmospheric Science', '1902', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Computers in Earth Sciences', '1903', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Earth-Surface Processes', '1904', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Economic Geology', '1905', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Geochemistry and Petrology', '1906', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Geology', '1907', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Geophysics', '1908', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Geotechnical Engineering and Engineering Geology', '1909', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Oceanography', '1910', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Palaeontology', '1911', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Space and Planetary Science', '1912', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Stratigraphy', '1913', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Economics, Econometrics and Finance', '2000', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Economics, Econometrics and Finance (miscellaneous)', '2001', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Economics and Econometrics', '2002', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Finance', '2003', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Energy', '2100', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Energy (miscellaneous)', '2101', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Energy Engineering and Power Technology', '2102', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Fuel Technology', '2103', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Nuclear Energy and Engineering', '2104', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Renewable Energy, Sustainability and the Environment', '2105', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Engineering', '2200', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Engineering (miscellaneous)', '2201', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Aerospace Engineering', '2202', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Automotive Engineering', '2203', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Biomedical Engineering', '2204', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Civil and Structural Engineering', '2205', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Computational Mechanics', '2206', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Control and Systems Engineering', '2207', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Electrical and Electronic Engineering', '2208', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Industrial and Manufacturing Engineering', '2209', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Mechanical Engineering', '2210', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Mechanics of Materials', '2211', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Ocean Engineering', '2212', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Safety, Risk, Reliability and Quality', '2213', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Media Technology', '2214', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Building and Construction', '2215', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Architecture ', '2216', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Environmental Science', '2300', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Environmental Science (miscellaneous)', '2301', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Ecological Modelling', '2302', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Ecology', '2303', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Environmental Chemistry', '2304', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Environmental Engineering', '2305', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Global and Planetary Change', '2306', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Health, Toxicology and Mutagenesis', '2307', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Management, Monitoring, Policy and Law', '2308', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Nature and Landscape Conservation', '2309', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Pollution', '2310', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Waste Management and Disposal', '2311', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Water Science and Technology', '2312', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('General Immunology and Microbiology', '2400', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Immunology and Microbiology (miscellaneous) ', '2401', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Applied Microbiology and Biotechnology', '2402', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Immunology', '2403', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Microbiology', '2404', 'ASJC');
      insert into classifications (name, identifier, scheme) values ('Parasitology', '2405', 'ASJC');
     